# Generated by Django 5.2.12 on 2026-06-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejissior',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
