# Generated by Django 5.2.12 on 2026-06-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='api.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rejissior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='api.rejissior'),
        ),
    ]
